# Site settings
title: Candy Coated Syntax
email: "garthdb@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  A collection of design and development lessons (mostly front end) I've learned while trying to get the web to do what I want.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://candycoatedsyntax.com" # the base hostname & protocol for your site
github_username: garthdb
twitter_username: garthdb
exclude:
  - vendor
  - README.md
  - LICENSE
  - CNAME
  - .markdownlintrc

# Build settings
markdown: kramdown

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      author: "garthdb"
